version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/cis476-term-project/term-project-frontend
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/cis476-term-project/backend-server
    command: ["npm", "run", "start"]
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:your_password@postgres:5432/your_database_name
      # other environment variables as needed

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
